### PR TITLE
Tower group

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
I did a review and found that it wasn't invoking our example/test playbook, which you likely didn't know about, if the checks pass merge this into your code and we can then finish your PR.

### CODE REVIEW

**Comment by sean-m-sullivan** [comment]
Updated the testing, Did other tweaks please review and merge to your branch this will update your PR and we can get it into the project.

**Comment by weiyentan** [comment]
@sean-m-sullivan  thanks for this. I think it correct. I apologise if there was any issues. It's my first time creating a github pt. I tend to work with gitlab.

Hopefully I did it correctly.

**Comment by sean-m-sullivan** [comment]
@weiyentan 
It's no problem, I was like I could likely respond and point out all the individual parts of the code that needed tweaked, or I could probably spend just about the same time adding those parts. The place where we pull testing from is non obvious and we are working on fixing that.

**Comment by weiyentan** [comment]
Thank you. Did I do the merge correctly? I am not sure what I have to do now.

**Comment by weiyentan** [comment]
Do I submit a pr from my branch again?

**Comment by sean-m-sullivan** [comment]
I believe it is completed, Your Branch when updated updated the PR you made, so being Merging this one, which was done correctly, it automatically updated your previous PR. Like Dominoes :), So all the work is done and Groups role is now in our devel branch

**Pull request merged**
